export  const collections = [
    {
      id: 1,
      name: "Native Wears",
      description: "Elegant traditional wear with contemporary flair",
      image: "/native.jpg",
      products: [
        {
          id: 101,
          title: "Agbada Set",
          description: "Traditional Nigerian formal attire with modern styling",
          image: "/native-1.jpg",
          category: "Native",
          price: "$299",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL", "XXL"],
          colors: ["Blue", "Green", "Gold", "Red"],
          inStock: true,
        },
        {
          id: 102,
          title: "Senator Suit",
          description:
            "Contemporary take on the classic Nigerian senator attire",
          image: "/native-2.jpg",
          category: "Native",
          price: "$249",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Black", "Navy", "Brown", "Grey"],
          inStock: true,
        },
        {
          id: 103,
          title: "Buba and Sokoto",
          description: "Traditional two-piece set with intricate embroidery",
          image: "/native-3.jpg",
          category: "Native",
          price: "$199",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Blue", "Green", "Red"],
          inStock: true,
        },
        {
          id: 104,
          title: "Dashiki",
          description: "Vibrant patterned shirt with cultural significance",
          image: "/native-4.jpg",
          category: "Native",
          price: "$149",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Multi-color", "Blue", "Green", "Red"],
          inStock: true,
        },
        {
          id: 105,
          title: "Yoruba Agbada",
          description: "Traditional Yoruba formal attire with intricate embroidery",
          image: "/native-5.jpg",
          category: "Native",
          price: "$329",
          featured: true,
          type: "collection",
          sizes: ["M", "L", "XL", "XXL"],
          colors: ["White", "Blue", "Gold", "Green"],
          inStock: true,
        },
        {
          id: 106,
          title: "Igbo Isiagu",
          description: "Traditional Igbo attire with lion head pattern",
          image: "/native-6.jpg",
          category: "Native",
          price: "$279",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Red", "Black", "Gold", "Green"],
          inStock: true,
        },
        {
          id: 107,
          title: "Hausa Babban Riga",
          description: "Traditional Hausa flowing gown with detailed embroidery",
          image: "/native-7.jpg",
          category: "Native",
          price: "$259",
          featured: false,
          type: "collection",
          sizes: ["M", "L", "XL", "XXL"],
          colors: ["White", "Blue", "Green", "Red"],
          inStock: true,
        },
        {
          id: 108,
          title: "Modern Kaftan",
          description: "Contemporary kaftan with traditional elements",
          image: "/native-8.jpg",
          category: "Native",
          price: "$189",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Blue", "Green", "Red"],
          inStock: true,
        },
      ],
    },
    {
      id: 2,
      name: "FASHIO Signature Caps",
      description: "Our iconic collection of premium headwear",
      image: "/cap.jpg",
      products: [
        {
          id: 201,
          title: "Classic Baseball Cap",
          description: "Timeless design with premium materials",
          image: "/cap-1.jpg",
          category: "Accessories",
          price: "$49",
          featured: true,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "White", "Grey"],
          inStock: true,
        },
        {
          id: 202,
          title: "Snapback Cap",
          description: "Modern style with adjustable snap closure",
          image: "/cap-2.jpg",
          category: "Accessories",
          price: "$59",
          featured: true,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Red", "Green"],
          inStock: true,
        },
        {
          id: 203,
          title: "Flat Cap",
          description: "Sophisticated design for the discerning gentleman",
          image: "/cap-3.jpg",
          category: "Accessories",
          price: "$69",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Brown", "Grey", "Black", "Navy"],
          inStock: true,
        },
        {
          id: 204,
          title: "Visor",
          description: "Sporty design with adjustable strap",
          image: "/cap-4.jpg",
          category: "Accessories",
          price: "$39",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "White", "Navy", "Red"],
          inStock: true,
        },
        {
          id: 205,
          title: "FASHIO Logo Cap",
          description: "Premium cap featuring our signature logo",
          image: "/cap-5.jpg",
          category: "Accessories",
          price: "$54",
          featured: true,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "White", "Red"],
          inStock: true,
        },
        {
          id: 206,
          title: "Trucker Cap",
          description: "Classic mesh-backed cap with structured front",
          image: "/cap-6.jpg",
          category: "Accessories",
          price: "$49",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Grey", "Green"],
          inStock: true,
        },
        {
          id: 207,
          title: "Beanie",
          description: "Warm and stylish beanie for colder weather",
          image: "/cap-7.jpg",
          category: "Accessories",
          price: "$39",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Grey", "Burgundy"],
          inStock: true,
        },
        {
          id: 208,
          title: "Panama Hat",
          description: "Elegant straw hat for summer occasions",
          image: "/cap-8.jpg",
          category: "Accessories",
          price: "$79",
          featured: true,
          type: "retail",
          sizes: ["S", "M", "L"],
          colors: ["Natural", "Black", "White"],
          inStock: true,
        },
      ],
    },
    {
      id: 3,
      name: "Groomsmen Attire",
      description: "Elegant ensembles for the special day",
      image: "/groomsmen-collection.jpg",
      products: [
        {
          id: 301,
          title: "Classic Tuxedo",
          description: "Timeless elegance for formal occasions",
          image: "/groomsmen-1.jpg",
          category: "Formal",
          price: "$399",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Black", "Navy", "Burgundy"],
          inStock: true,
        },
        {
          id: 302,
          title: "Three-Piece Suit",
          description: "Complete ensemble with vest for a polished look",
          image: "/groomsmen-2.jpg",
          category: "Formal",
          price: "$349",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Grey", "Navy", "Charcoal"],
          inStock: true,
        },
        {
          id: 303,
          title: "Formal Shirt",
          description: "Premium cotton shirt with French cuffs",
          image: "/groomsmen-3.jpg",
          category: "Formal",
          price: "$129",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Light Blue", "Pink"],
          inStock: true,
        },
        {
          id: 304,
          title: "Bow Tie Set",
          description: "Classic bow tie with matching pocket square",
          image: "/groomsmen-4.jpg",
          category: "Accessories",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Burgundy", "Grey"],
          inStock: true,
        },
        {
          id: 305,
          title: "Wedding Tuxedo",
          description: "Premium tuxedo with satin lapels for the groom",
          image: "/groomsmen-5.jpg",
          category: "Formal",
          price: "$449",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Black", "Navy", "Burgundy"],
          inStock: true,
        },
        {
          id: 306,
          title: "Groomsmen Suit",
          description: "Matching suits for the entire wedding party",
          image: "/groomsmen-6.jpg",
          category: "Formal",
          price: "$329",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Burgundy"],
          inStock: true,
        },
        {
          id: 307,
          title: "Wedding Accessories Set",
          description: "Complete set of accessories for the wedding day",
          image: "/groomsmen-7.jpg",
          category: "Accessories",
          price: "$149",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Black", "Navy", "Burgundy"],
          inStock: true,
        },
        {
          id: 308,
          title: "Formal Shoes",
          description: "Classic oxford shoes for formal occasions",
          image: "/groomsmen-8.jpg",
          category: "Footwear",
          price: "$199",
          featured: false,
          type: "retail",
          sizes: ["7", "8", "9", "10", "11", "12"],
          colors: ["Black", "Brown", "Tan"],
          inStock: true,
        },
      ],
    },
    {
      id: 4,
      name: "Bespoke Collection",
      description: "Tailored to perfection for the modern gentleman",
      image: "/bespoke-collection.jpg",
      products: [
        {
          id: 401,
          title: "Custom Suit",
          description: "Fully customizable suit made to your measurements",
          image: "/bespoke-1.jpg",
          category: "Suits",
          price: "From $499",
          featured: true,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 402,
          title: "Bespoke Shirt",
          description: "Handcrafted shirt tailored to your preferences",
          image: "/bespoke-2.jpg",
          category: "Shirts",
          price: "From $199",
          featured: true,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 403,
          title: "Custom Blazer",
          description: "Tailored blazer for a perfect fit",
          image: "/bespoke-3.jpg",
          category: "Outerwear",
          price: "From $299",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 404,
          title: "Bespoke Trousers",
          description: "Custom-fitted trousers for comfort and style",
          image: "/bespoke-4.jpg",
          category: "Trousers",
          price: "From $149",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 405,
          title: "Bespoke Tuxedo",
          description: "Custom-made tuxedo for special occasions",
          image: "/bespoke-5.jpg",
          category: "Formal",
          price: "From $599",
          featured: true,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 406,
          title: "Custom Overcoat",
          description: "Tailored overcoat for winter elegance",
          image: "/bespoke-6.jpg",
          category: "Outerwear",
          price: "From $349",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 407,
          title: "Bespoke Waistcoat",
          description: "Custom-fitted waistcoat to complete your ensemble",
          image: "/bespoke-7.jpg",
          category: "Formal",
          price: "From $199",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 408,
          title: "Custom Dress Shirt",
          description: "Tailored dress shirt with personalized details",
          image: "/bespoke-8.jpg",
          category: "Shirts",
          price: "From $179",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
      ],
    },
    {
      id: 5,
      name: "Casual Collection",
      description: "Effortlessly stylish everyday wear",
      image: "/casual-collection.jpg",
      products: [
        {
          id: 501,
          title: "Denim Jacket",
          description: "Classic design with modern details",
          image: "/casual-1.jpg",
          category: "Outerwear",
          price: "$129",
          featured: true,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Blue", "Black", "Grey"],
          inStock: true,
        },
        {
          id: 502,
          title: "Chino Pants",
          description: "Versatile pants for any casual occasion",
          image: "/casual-2.jpg",
          category: "Trousers",
          price: "$89",
          featured: true,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38"],
          colors: ["Khaki", "Navy", "Olive", "Black"],
          inStock: true,
        },
        {
          id: 503,
          title: "Polo Shirt",
          description: "Classic polo with premium materials",
          image: "/casual-3.jpg",
          category: "Shirts",
          price: "$69",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Navy", "Red", "Black"],
          inStock: true,
        },
        {
          id: 504,
          title: "Henley Shirt",
          description: "Casual button-down with a relaxed fit",
          image: "/casual-4.jpg",
          category: "Shirts",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Grey", "Navy", "Burgundy"],
          inStock: true,
        },
        {
          id: 505,
          title: "Slim Fit Jeans",
          description: "Modern slim fit jeans with premium denim",
          image: "/casual-5.jpg",
          category: "Trousers",
          price: "$99",
          featured: true,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38"],
          colors: ["Blue", "Black", "Grey"],
          inStock: true,
        },
        {
          id: 506,
          title: "Casual Blazer",
          description: "Versatile blazer for smart casual occasions",
          image: "/casual-6.jpg",
          category: "Outerwear",
          price: "$159",
          featured: true,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Khaki", "Black"],
          inStock: true,
        },
        {
          id: 507,
          title: "Graphic T-Shirt",
          description: "Stylish graphic tee with unique designs",
          image: "/casual-7.jpg",
          category: "Shirts",
          price: "$49",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Black", "Grey", "Navy"],
          inStock: true,
        },
        {
          id: 508,
          title: "Cargo Pants",
          description: "Functional cargo pants with multiple pockets",
          image: "/casual-8.jpg",
          category: "Trousers",
          price: "$89",
          featured: false,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38"],
          colors: ["Khaki", "Olive", "Black", "Navy"],
          inStock: true,
        },
      ],
    },
    {
      id: 6,
      name: "Accessories",
      description: "Complete your look with our premium accessories",
      image: "/accessories-collection.jpg",
      products: [
        {
          id: 601,
          title: "Leather Belt",
          description: "Genuine leather belt with classic buckle",
          image: "/accessories-1.jpg",
          category: "Accessories",
          price: "$59",
          featured: true,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38", "40"],
          colors: ["Brown", "Black", "Tan"],
          inStock: true,
        },
        {
          id: 602,
          title: "Silk Tie",
          description: "Premium silk tie with elegant pattern",
          image: "/accessories-2.jpg",
          category: "Accessories",
          price: "$49",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Navy", "Burgundy", "Green", "Purple"],
          inStock: true,
        },
        {
          id: 603,
          title: "Pocket Square",
          description: "Folded pocket square for a polished look",
          image: "/accessories-3.jpg",
          category: "Accessories",
          price: "$29",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["White", "Navy", "Red", "Green"],
          inStock: true,
        },
        {
          id: 604,
          title: "Cufflinks",
          description: "Elegant cufflinks for formal occasions",
          image: "/accessories-4.jpg",
          category: "Accessories",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Silver", "Gold", "Rose Gold"],
          inStock: true,
        },
        {
          id: 605,
          title: "Leather Wallet",
          description: "Premium leather wallet with multiple card slots",
          image: "/accessories-5.jpg",
          category: "Accessories",
          price: "$69",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Brown", "Black", "Tan"],
          inStock: true,
        },
        {
          id: 606,
          title: "Sunglasses",
          description: "Stylish sunglasses with UV protection",
          image: "/accessories-6.jpg",
          category: "Accessories",
          price: "$89",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Black", "Brown", "Tortoise", "Gold"],
          inStock: true,
        },
        {
          id: 607,
          title: "Leather Gloves",
          description: "Premium leather gloves for cold weather",
          image: "/accessories-7.jpg",
          category: "Accessories",
          price: "$59",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Brown", "Black", "Tan"],
          inStock: true,
        },
        {
          id: 608,
          title: "Scarf",
          description: "Warm and stylish scarf for winter",
          image: "/accessories-8.jpg",
          category: "Accessories",
          price: "$49",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Navy", "Grey", "Burgundy", "Green"],
          inStock: true,
        },
      ],
    },
    {
      id: 7,
      name: "Luxury Watches",
      description: "Timeless timepieces for the distinguished gentleman",
      image: "/watch.jpg",
      products: [
        {
          id: 701,
          title: "Classic Chronograph",
          description: "Elegant chronograph with leather strap",
          image: "/watch.jpg",
          category: "Watches",
          price: "$299",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Silver", "Gold", "Rose Gold"],
          inStock: true,
        },
        {
          id: 702,
          title: "Minimalist Watch",
          description: "Clean, minimalist design with mesh band",
          image: "/watch.jpg",
          category: "Watches",
          price: "$199",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Silver", "Gold", "Black"],
          inStock: true,
        },
        {
          id: 703,
          title: "Diver Watch",
          description: "Water-resistant watch with rotating bezel",
          image: "/watch.jpg",
          category: "Watches",
          price: "$249",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Black", "Blue", "Silver"],
          inStock: true,
        },
        {
          id: 704,
          title: "Luxury Timepiece",
          description: "Premium watch with diamond accents",
          image: "/watch.jpg",
          category: "Watches",
          price: "$599",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Gold", "Rose Gold", "Silver"],
          inStock: true,
        },
        {
          id: 705,
          title: "Smart Watch",
          description: "Modern smartwatch with fitness tracking",
          image: "/watch.jpg",
          category: "Watches",
          price: "$199",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Black", "Silver", "Gold"],
          inStock: true,
        },
        {
          id: 706,
          title: "Pilot Watch",
          description: "Aviation-inspired watch with chronograph",
          image: "/watch.jpg",
          category: "Watches",
          price: "$279",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Black", "Brown", "Silver"],
          inStock: true,
        },
        {
          id: 707,
          title: "Dress Watch",
          description: "Elegant timepiece for formal occasions",
          image: "/watch.jpg",
          category: "Watches",
          price: "$229",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Gold", "Silver", "Rose Gold"],
          inStock: true,
        },
        {
          id: 708,
          title: "Limited Edition Watch",
          description: "Exclusive timepiece with unique design",
          image: "/watch.jpg",
          category: "Watches",
          price: "$499",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Gold", "Silver", "Black"],
          inStock: true,
        },
      ],
    },
    {
      id: 8,
      name: "Two-Piece Sets",
      description: "Coordinated ensembles for a polished look",
      image: "/2piece.jpg",
      products: [
        {
          id: 801,
          title: "Classic Two-Piece Suit",
          description: "Timeless two-piece suit for formal occasions",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$9",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Black", "Charcoal"],
          inStock: true,
        },
        {
          id: 802,
          title: "Linen Two-Piece",
          description: "Lightweight linen suit for summer elegance",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$7",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Beige", "Light Blue", "White", "Khaki"],
          inStock: true,
        },
        {
          id: 803,
          title: "Patterned Two-Piece",
          description: "Bold patterned suit for a statement look",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$329",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Blue", "Green", "Burgundy", "Brown"],
          inStock: true,
        },
        {
          id: 804,
          title: "Slim Fit Two-Piece",
          description: "Modern slim fit suit for a contemporary look",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$299",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Black", "Charcoal"],
          inStock: true,
        },
        {
          id: 805,
          title: "Tweed Two-Piece",
          description: "Classic tweed suit for a traditional look",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$349",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Brown", "Green", "Grey", "Navy"],
          inStock: true,
        },
        {
          id: 806,
          title: "Casual Two-Piece",
          description: "Relaxed fit two-piece for smart casual occasions",
          image: "/two-piece-6.jpg",
          category: "Suits",
          price: "$259",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Khaki", "Black"],
          inStock: true,
        },
        {
          id: 807,
          title: "Velvet Two-Piece",
          description: "Luxurious velvet suit for special occasions",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$379",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Burgundy", "Navy", "Green", "Black"],
          inStock: true,
        },
        {
          id: 808,
          title: "Double-Breasted Two-Piece",
          description: "Classic double-breasted suit for a bold statement",
          image: "/2piece.jpg",
          category: "Suits",
          price: "$349",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Navy", "Grey", "Black", "Charcoal"],
          inStock: true,
        },
      ],
    },
  ];