export  const collections = [
    {
      id: 1,
      name: "Native Wears",
      description: "Elegant traditional wear with contemporary flair",
      image: "/native.jpg",
      products: [
        {
          id: 101,
          title: "Agbada Set",
          description: "Traditional Nigerian formal attire with modern styling",
          image: "/native-1.jpg",
          category: "Native",
          price: "$299",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL", "XXL"],
          colors: ["Blue", "Green", "Gold", "Red"],
          inStock: true,
        },
        {
          id: 102,
          title: "Senator Suit",
          description:
            "Contemporary take on the classic Nigerian senator attire",
          image: "/native-2.jpg",
          category: "Native",
          price: "$249",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Black", "Navy", "Brown", "Grey"],
          inStock: true,
        },
        {
          id: 103,
          title: "Buba and Sokoto",
          description: "Traditional two-piece set with intricate embroidery",
          image: "/native-3.jpg",
          category: "Native",
          price: "$199",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Blue", "Green", "Red"],
          inStock: true,
        },
        {
          id: 104,
          title: "Dashiki",
          description: "Vibrant patterned shirt with cultural significance",
          image: "/native-4.jpg",
          category: "Native",
          price: "$149",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Multi-color", "Blue", "Green", "Red"],
          inStock: true,
        },
      ],
    },
    {
      id: 2,
      name: "FASHIO Signature Caps",
      description: "Our iconic collection of premium headwear",
      image: "/cap.jpg",
      products: [
        {
          id: 201,
          title: "Classic Baseball Cap",
          description: "Timeless design with premium materials",
          image: "/cap-1.jpg",
          category: "Accessories",
          price: "$49",
          featured: true,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "White", "Grey"],
          inStock: true,
        },
        {
          id: 202,
          title: "Snapback Cap",
          description: "Modern style with adjustable snap closure",
          image: "/cap-2.jpg",
          category: "Accessories",
          price: "$59",
          featured: true,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Red", "Green"],
          inStock: true,
        },
        {
          id: 203,
          title: "Flat Cap",
          description: "Sophisticated design for the discerning gentleman",
          image: "/cap-3.jpg",
          category: "Accessories",
          price: "$69",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Brown", "Grey", "Black", "Navy"],
          inStock: true,
        },
        {
          id: 204,
          title: "Visor",
          description: "Sporty design with adjustable strap",
          image: "/cap-4.jpg",
          category: "Accessories",
          price: "$39",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "White", "Navy", "Red"],
          inStock: true,
        },
      ],
    },
    {
      id: 3,
      name: "Groomsmen Attire",
      description: "Elegant ensembles for the special day",
      image: "/groomsmen-collection.jpg",
      products: [
        {
          id: 301,
          title: "Classic Tuxedo",
          description: "Timeless elegance for formal occasions",
          image: "/groomsmen-1.jpg",
          category: "Formal",
          price: "$399",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Black", "Navy", "Burgundy"],
          inStock: true,
        },
        {
          id: 302,
          title: "Three-Piece Suit",
          description: "Complete ensemble with vest for a polished look",
          image: "/groomsmen-2.jpg",
          category: "Formal",
          price: "$349",
          featured: true,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Grey", "Navy", "Charcoal"],
          inStock: true,
        },
        {
          id: 303,
          title: "Formal Shirt",
          description: "Premium cotton shirt with French cuffs",
          image: "/groomsmen-3.jpg",
          category: "Formal",
          price: "$129",
          featured: false,
          type: "collection",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Light Blue", "Pink"],
          inStock: true,
        },
        {
          id: 304,
          title: "Bow Tie Set",
          description: "Classic bow tie with matching pocket square",
          image: "/groomsmen-4.jpg",
          category: "Accessories",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["One Size"],
          colors: ["Black", "Navy", "Burgundy", "Grey"],
          inStock: true,
        },
      ],
    },
    {
      id: 4,
      name: "Bespoke Collection",
      description: "Tailored to perfection for the modern gentleman",
      image: "/bespoke-collection.jpg",
      products: [
        {
          id: 401,
          title: "Custom Suit",
          description: "Fully customizable suit made to your measurements",
          image: "/bespoke-1.jpg",
          category: "Suits",
          price: "From $499",
          featured: true,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 402,
          title: "Bespoke Shirt",
          description: "Handcrafted shirt tailored to your preferences",
          image: "/bespoke-2.jpg",
          category: "Shirts",
          price: "From $199",
          featured: true,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 403,
          title: "Custom Blazer",
          description: "Tailored blazer for a perfect fit",
          image: "/bespoke-3.jpg",
          category: "Outerwear",
          price: "From $299",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
        {
          id: 404,
          title: "Bespoke Trousers",
          description: "Custom-fitted trousers for comfort and style",
          image: "/bespoke-4.jpg",
          category: "Trousers",
          price: "From $149",
          featured: false,
          type: "collection",
          sizes: ["Custom"],
          colors: ["Custom"],
          inStock: true,
        },
      ],
    },
    {
      id: 5,
      name: "Casual Collection",
      description: "Effortlessly stylish everyday wear",
      image: "/casual-collection.jpg",
      products: [
        {
          id: 501,
          title: "Denim Jacket",
          description: "Classic design with modern details",
          image: "/casual-1.jpg",
          category: "Outerwear",
          price: "$129",
          featured: true,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["Blue", "Black", "Grey"],
          inStock: true,
        },
        {
          id: 502,
          title: "Chino Pants",
          description: "Versatile pants for any casual occasion",
          image: "/casual-2.jpg",
          category: "Trousers",
          price: "$89",
          featured: true,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38"],
          colors: ["Khaki", "Navy", "Olive", "Black"],
          inStock: true,
        },
        {
          id: 503,
          title: "Polo Shirt",
          description: "Classic polo with premium materials",
          image: "/casual-3.jpg",
          category: "Shirts",
          price: "$69",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Navy", "Red", "Black"],
          inStock: true,
        },
        {
          id: 504,
          title: "Henley Shirt",
          description: "Casual button-down with a relaxed fit",
          image: "/casual-4.jpg",
          category: "Shirts",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["S", "M", "L", "XL"],
          colors: ["White", "Grey", "Navy", "Burgundy"],
          inStock: true,
        },
      ],
    },
    {
      id: 6,
      name: "Accessories",
      description: "Complete your look with our premium accessories",
      image: "/accessories-collection.jpg",
      products: [
        {
          id: 601,
          title: "Leather Belt",
          description: "Genuine leather belt with classic buckle",
          image: "/accessories-1.jpg",
          category: "Accessories",
          price: "$59",
          featured: true,
          type: "retail",
          sizes: ["30", "32", "34", "36", "38", "40"],
          colors: ["Brown", "Black", "Tan"],
          inStock: true,
        },
        {
          id: 602,
          title: "Silk Tie",
          description: "Premium silk tie with elegant pattern",
          image: "/accessories-2.jpg",
          category: "Accessories",
          price: "$49",
          featured: true,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Navy", "Burgundy", "Green", "Purple"],
          inStock: true,
        },
        {
          id: 603,
          title: "Pocket Square",
          description: "Folded pocket square for a polished look",
          image: "/accessories-3.jpg",
          category: "Accessories",
          price: "$29",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["White", "Navy", "Red", "Green"],
          inStock: true,
        },
        {
          id: 604,
          title: "Cufflinks",
          description: "Elegant cufflinks for formal occasions",
          image: "/accessories-4.jpg",
          category: "Accessories",
          price: "$79",
          featured: false,
          type: "retail",
          sizes: ["Standard"],
          colors: ["Silver", "Gold", "Rose Gold"],
          inStock: true,
        },
      ],
    },
  ];